### ISSUE TITLE
Add support for ititle identifier type

### ISSUE THREAD

**Issue by fpayer** [aasmal97/Window-Actions#1]
There is currently no way to minimize/maximize a window by a substring match of the window title.

Selecting the "Window Title" identifier type executes the nircmd with the command `win {min|max} title {name}`. This command requires an exact match of the window title. However, I would like to select a window using a partial match because I'm trying to select a window that dynamically updates a portion of the title. 

I would like to suggest adding a new Identifier Type for a partial window title match that will execute nircmd with `win {min|max} ititle {name}`, which will support a partial match on the window title. I believe this change should only require a small update to the [commands.js](https://github.com/aasmal97/Window-Actions/blob/master/Sources/com.arkyasmal.windowActions.sdPlugin/app/nodeExecCommands/commands.js) and [index.html](https://github.com/aasmal97/Window-Actions/blob/f1b3b83cfc9bdd6de11141a1d4c32472dc1d761e/Sources/com.arkyasmal.windowActions.sdPlugin/propertyinspector/index.html)

**Comment by aasmal97** [comment]
I agree! I'll create a new branch to implement this.

**Comment by aasmal97** [comment]
This is updated! You can wait for Elgato to update the app version in their store, or download the v1.2 rlease file

**Comment by fpayer** [comment]
Wow that was quick! Thanks so much. 

How long do you think it'll take Elgato to update the app version in the store?

**Comment by aasmal97** [comment]
Usually takes 1-2 weeks. However, the current version can be downloaded straight from github,  [here](https://github.com/aasmal97/Window-Actions/releases/tag/v1.2.0. )
