### ISSUE TITLE
Virtual desktop actions broken in Windows 11 22635.2921

### ISSUE THREAD

**Issue by upadsamay387** [aasmal97/Window-Actions#11]
I see this referenced in the VirtualDesktopAccessor repository, and it seems to already be fixed.

https://github.com/Ciantic/VirtualDesktopAccessor/issues/81#issuecomment-1865102906

**Comment by aasmal97** [comment]
Thank for letting me know :) ! I'll add and update the dll file for a new release :) . Windows updates are killing us 😭

**Comment by upadsamay387** [comment]
@aasmal97 

Hi! I haven't tested too thoroughly, but so far it looks good!

Thanks for the fix. It's really appreciated given that this is an insider-specific issue as of right now.
