### ISSUE TITLE
Virtual Desktop Actions Not Working After Win11 Feb 2024 Update

### ISSUE THREAD

**Issue by applegeeks** [aasmal97/Window-Actions#12]
Not sure if previously closed items are being tracked still so opening a new one here.
To reference 
https://github.com/aasmal97/Window-Actions/issues/7#issuecomment-1948280135

Issue with Virtual Desktop buttons not working post Win11 Feb 2024 update
Running Windows ACtions 4.1.0
Edition Windows 11
Version 22H2
OS build 22621.3155

**Comment by aasmal97** [comment]
All good! So the oldest version that doesn't work is `22621.3155` right? Want to ensure so I can write the proper conditional logic for the binary :) ! @applegeeks

**Comment by applegeeks** [comment]
> All good! So the oldest version that doesn't work is `22621.3155` right? Want to ensure so I can write the proper conditional logic for the binary :) ! @applegeeks

Thanks for the quick response.
And yes, that's the right version post Feb 2024 update.

**Comment by aasmal97** [comment]
Just created a new release 4.1.1, to patch this. Feel free to download the release file [here](https://github.com/aasmal97/Window-Actions/releases/tag/v4.1.1).

The marketplace will be updated in 1-2 weeks (that's usually the processing time)

No need to worry about auto-updates, as downloading the release file from the current link will not stop any future updates.

**Comment by applegeeks** [comment]
> @applegeeks Just created a new release 4.1.1, to patch this. Feel free to download the release file [here](https://github.com/aasmal97/Window-Actions/releases/tag/v4.1.1).
> 
> The marketplace will be updated in 1-2 weeks (that's usually the processing time)
> 
> No need to worry about auto-updates, as downloading the release file from the current link will not stop any future updates.

absolute LEGENT and so quick!
Thank you so much.

Downloaded and  confirmed working now with Feb 2024 update.
