### ISSUE TITLE
Virtual Desktop Actions - Support in Win11 23H2?

### ISSUE THREAD

**Issue by applegeeks** [aasmal97/Window-Actions#14]
@aasmal97, got the notification for the Win11 23H2 Update across a few of the systems today.
Do you know if Virtual Desktop Actions will break or is supported with this upcoming update?
![image](https://github.com/aasmal97/Window-Actions/assets/98582882/5affd50e-e740-4321-93c0-1881b1b8025d)

**Comment by applegeeks** [comment]
Can be closed. Took the plunge and updated to 23H2 and plugin still worked without issues.

**Comment by aasmal97** [comment]
@applegeeks Awesome to know! And thank you for reporting these, as I don't always have the time to keep up with the changes haha :) !
