### ISSUE TITLE
Screen/Monitor names not being shown in the screen: dropdown menu 

### ISSUE THREAD

**Issue by Reberebe** [aasmal97/Window-Actions#17]
**Plugin Name:** Windows-Action: Move Window To New Monitor/Screen 
**Stream Deck Model:** Stream Deck XL 

**Description of Problem:**  I was using Windows Mover for a while, but last week, when trying to use the keys (Which I used to move windows to different screens or sections of the screens) I started getting a ⚠️
After reading the trouble shooting site, I noticed that the screens are not being displayed in the drop down menu of the plugin, while troubleshooting I tried other alternatives 
WIndows-Action being one of them, but the same problem persisted, I noticed that in both plugins the drop down menu for selecting the main screen wouldn't show my screen names, 
![image](https://github.com/user-attachments/assets/b6edc92f-5fdb-4781-b38b-a0fb5b320d7b)
(the dropdown arrow has been pressed in that screencap) 

**Troubleshooting Done:**
-Installing and re-installing plugins (both of them) 
-Installing and re-installing stream deck 
-Installing and re-installing/updating Nvidia Drivers
-I read on the bar raider troubleshooting that a software called "team Viewer" could cause that, I make sure I don't have that installed 

Other than that I found two reddit posts with that issue 
https://www.reddit.com/r/elgato/comments/1euaaeu/streamdeck_barraider_windows_mover/
and I made a different one
https://www.reddit.com/r/elgato/comments/1g3tk9i/stream_deck_plugins_not_detecting_screen_names/
(Thanks again for answering there) 

I know there was a windows updated after I came back that week, alongside some things I installed, 
Windows 10 Home, **version**:22H2  **Build**: 19045.5011

Other than that, I ran[ youtube music ](https://github.com/th-ch/youtube-music?tab=readme-ov-file)
and I think that update and trying that software are the only things that changed from when it worked and when I noticed it stopped working

**Comment by aasmal97** [comment]
Cool! I'll take a this weekend and see what I can find. 

Can I also get the monitors you are using? The product name with they year, should be enough. Usually this can be found on the back of the monitors :) !

**Comment by Reberebe** [comment]
Absolutely:
•**Monitors**: 
VG248QG Version VG248QG August 2020 (Main display)
VG245       Version VG245HE December 2018
VG245       Version VG245H   January 2019

I have a TV connected as well 
Sony XBR-55X81CH  September 2021

and a drawing tablet
XP-PEN  22 plus (MD-220FH)  
which I usually only have either the TV or the drawing tablet active, never both since my GPU only allows for 4 simultaneous displays
(When I have the drawing tablet I have it in **Duplicate** mode, while the TV is in the **Extend** mode when pressing Windows+P) 


**•Stream Deck:**  6.7.3 (21005)
![image](https://github.com/user-attachments/assets/7ad7072c-dc42-4702-8262-1186aff964b5)

**Comment by aasmal97** [comment]
@Reberebe Hey! Sorry about the long wait, but I found some time to try to debug your issue today. 

So after running this on a Windows 10 Machine with the same verison, I did see that an update some Window's DLL logic might have been causing the plugin to silently crash. I updated this, and everyone was working fine. Before I push this to production, I want to ensure this will fix your issue.

Please follow the following steps:
1. Complete clear you computer of your current Window Actions plugin:
    - [ ] Close and exit out the StreamDeck app completely (Force quit in the bottom mini toolbar as well)
    - [ ] Open up Task Manager.
    - [ ] In Task Manager please FORCE QUIT a program called `run.exe`. It should have floppy disk icon next to it
    - [ ] Open up File Explorer, and in the search bar, write the following command 
    `%APPDATA%/Elgato/StreamDeck/Plugins`. Find 'com.arkyasmal.windowactions.sdPlugin' and completely delete the directory
    This is a video of me going through this process:

2. Install the new release file 
  - [ ] Download the [following new testing release file](https://github.com/aasmal97/Window-Actions/blob/development/Release/com.arkyasmal.windowactions.streamDeckPlugin). Don't worry, downloading this release from here will not stop the auto-updates from Elgato. You can download it by clicking the link above, and clicking on the three dots on the top right.

3. Try to find your windows through the dropdown again.

**Comment by aasmal97** [comment]
@Reberebe I'll be closing the issue because 4.2.1 is now on the Marketplace, and includes the fix :) ! If you encounter the same bug, feel free to re-open the issue
