### ISSUE TITLE
installs but isn't there or doesn't work with latest 6.05 stream deck software and windows 11

### ISSUE THREAD

**Issue by xnaron** [aasmal97/Window-Actions#3]
It installs but isn't there or doesn't work with latest 6.05 stream deck software and windows 11.  Running latest version.  The setup file linked on main page goes to a violates google terms of service page.  It was working fine before the Feb 21/2023 update.

**Comment by xnaron** [comment]
So it does install but it doesn't work.  Clicking on "Active Windows"  does not launch GuiPropView.  The program is there ..\AppData\Roaming\Elgato\StreamDeck\Plugins\com.arkyasmal.windowactions.sdPlugin\app\executables and does run if I start it there.  Minimize and Maximize do nothing.   I have tried it on two separate machines running 6.05 and windows 11 with latest plugin available on the elgato store from within the app.

**Comment by aasmal97** [comment]
The setup file link might be stale, I'll update it. The same setup file can be found [here though](https://github.com/aasmal97/Window-Actions/releases/tag/v1.2.0). Have you tried uninstalling, then re-installing the app? 

Although, I see that the partial title identifier does not work when you select from the dropdown. I'm going to look into it, and see if I can fix this functionality. 

Opening up a new branch. If there are other issues after re-installing please post them here

**Comment by xnaron** [comment]
Yes I have tried uninstalling and reinstalling on both machines.

**Comment by aasmal97** [comment]
Found the issue! Unsurprisingly this was a simple typo when checking a conditional. Sorry about that! This is why I ought to drink more coffee haha. Fixing it now, I'll release the new app soon :) ! 

![image_2023-02-22_184120044](https://user-images.githubusercontent.com/74555081/220788543-f3038c8f-d89f-4705-942d-ae5c686297db.png)

**Comment by xnaron** [comment]
Hahaha. Been there. Done that. :)

**Comment by aasmal97** [comment]
@xnaron

**Comment by xnaron** [comment]
It is working now!  Thank you!

**Comment by aasmal97** [comment]
Awesome! Yeah, I suspect the undefined input would cause the websocket server to crash since it's an unexpected value. Good to hear!
