### ISSUE TITLE
new version just doesn't work

### ISSUE THREAD

**Issue by pacopepepipo** [aasmal97/Window-Actions#8]
guipropview from nirsoft was deleted?

it sometimes fails with the new version the reposition/resize, and also without that tool is difficult to sometimes get the position and sizes of the window when creating a new one

it also, fails sometimes to just reposition when using 2 displays and previously worked without problems.

**Comment by aasmal97** [comment]
Yup! It became a security vulnerability, which caused issues with elgato's virus screening process, so I opted to delete it. You can always download it yourself separately though here :) https://www.nirsoft.net/utils/gui_prop_view.html

**Comment by aasmal97** [comment]
And I see about the occasional repositioning bug. Some of the logic has changed. We no longer use nircmd, but the Win32 API directly.

For follow-up debugging and testing: 

What version of windows are you using? 
What numerical inputs are placed into the x and y, when you're repositioning and it fails? 

Also have you tried deleting the action, and setting it up again? 
Sometimes it can be an input issue too.

**Comment by pacopepepipo** [comment]
@aasmal97 

Nothing more, dunno why but reinstalling the pluging and now works everything just fine

**Comment by aasmal97** [comment]
It happens! The underlying files probably got stale or corrupted. Re-installing fixed this. Glad to hear it works perfectly. I will now be closing this issue.
